// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKBhJCeoVIpeOdaL2tMyBrLEvwPZIo2iw',
    appId: '1:36599718108:web:c9d115b790a607fe3e1419',
    messagingSenderId: '36599718108',
    projectId: 'waste-management-flutter',
    authDomain: 'waste-management-flutter.firebaseapp.com',
    databaseURL: 'https://waste-management-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-flutter.appspot.com',
    measurementId: 'G-FQXBRF5Z2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQO3r_GtlFZkfz_DP0SaprP25qMfChVNc',
    appId: '1:36599718108:android:aa430a85e4384d093e1419',
    messagingSenderId: '36599718108',
    projectId: 'waste-management-flutter',
    databaseURL: 'https://waste-management-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGtrRKiJC4qqWroIQ6dXT7PEVGCSm0zp8',
    appId: '1:36599718108:ios:650c0945e8b14b953e1419',
    messagingSenderId: '36599718108',
    projectId: 'waste-management-flutter',
    databaseURL: 'https://waste-management-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-flutter.appspot.com',
    iosClientId: '36599718108-c3hl2oehpp5hk8s1iijq7mjt5tk88pb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGtrRKiJC4qqWroIQ6dXT7PEVGCSm0zp8',
    appId: '1:36599718108:ios:650c0945e8b14b953e1419',
    messagingSenderId: '36599718108',
    projectId: 'waste-management-flutter',
    databaseURL: 'https://waste-management-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'waste-management-flutter.appspot.com',
    iosClientId: '36599718108-c3hl2oehpp5hk8s1iijq7mjt5tk88pb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingFlutter',
  );
}
